In [1]:
import numpy as np
import h5py

The import of the file needs to be changed to reading from an online storage.

In [16]:
file = '/Users/emilia/Documents/Documents - UU101746/GitHub/Results/19_09_2023_13_26_35/LMAHeureuxPorosityDiff.hdf5'

f = h5py.File(file, 'r')

In [17]:
f.attrs.keys()

<KeysViewHDF5 ['CA0', 'CAIni', 'CC0', 'CCIni', 'D0Ca', 'DCO3', 'DCa', 'DeepLimit', 'KA', 'KC', 'N', 'Phi0', 'PhiInfty', 'PhiIni', 'PhiNR', 'ShallowLimit', 'Th', 'Tstar', 'Xstar', 'adaptive', 'b', 'backend', 'beta', 'cCO30', 'cCO3Ini', 'cCa0', 'cCaIni', 'ca0', 'ca00', 'co30', 'co300', 'controller', 'data_length', 'data_tracker_interval', 'dt', 'eps', 'field_attributes', 'k1', 'k2', 'k3', 'k4', 'live_plotting', 'm1', 'm2', 'max_depth', 'muA', 'n1', 'n2', 'outt', 'outx', 'package_version', 'plotting_interval', 'progress_tracker_interval', 'retinfo', 'rhoa', 'rhoc', 'rhos', 'rhos0', 'rhot', 'rhow', 'scheme', 'sedimentationrate', 'tmax', 'track_U_at_bottom']>

Values through time, on the surface:

In [58]:
c_Ca = np.array(f['data'][:,2,0])
c_CO3 = np.array(f['data'][:,3,0])
n = 2.80
m = 2.48
K_A = 10 ** -6.19
K_C = 10 ** -6.37

In [59]:
O_PC0 = (c_Ca * c_CO3 - 1)
O_PC0[O_PC0 < 0] = 0 # Clunky way of removing negatives, needs improving
O_PC0 = O_PC0 ** n

In [64]:
O_PC0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
O_DC0 = (1 - c_Ca * c_CO3) ** n

In [67]:
O_DC0

array([0.44830418, 0.39865632, 0.40081329, 0.40142029, 0.40100012,
       0.40044636, 0.40018556, 0.40042044, 0.40067679, 0.40072747,
       0.4005531 , 0.40040664, 0.40032499, 0.4004466 , 0.40044424,
       0.40040494, 0.4003863 , 0.40036992, 0.40042171, 0.4004416 ,
       0.40041605, 0.40045458, 0.40029377, 0.40035472, 0.40040687,
       0.4003759 , 0.40033681, 0.40038873, 0.40038003, 0.40038471,
       0.40039148, 0.40037155, 0.40035558, 0.40038074, 0.40035056,
       0.40035044, 0.40030208, 0.40037147, 0.40030277, 0.40027447,
       0.40041055, 0.4002687 , 0.40036782, 0.40035283, 0.4003242 ,
       0.40034573, 0.40035069, 0.40037723, 0.40039871, 0.40037036,
       0.40036451, 0.40035943, 0.4003324 , 0.40035021, 0.40033489,
       0.40038873, 0.40033506, 0.40038188, 0.40030524, 0.40037636,
       0.40033138, 0.40035875, 0.40036211, 0.40026262, 0.4003417 ,
       0.40040193, 0.40032765, 0.40035237, 0.40030536, 0.40030353,
       0.40036294, 0.40031588, 0.40040693, 0.40030007, 0.40034

In [68]:
O_PA = (c_Ca * c_CO3 * K_C/K_A - 1)

In [70]:
O_PA[O_PA < 0] = 0
O_PA = O_PA ** m

In [71]:
O_PA

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
O_DA = (1 - c_Ca * c_CO3 * K_C/K_A) ** m

In [75]:
O_DA

array([0.64017051, 0.6021623 , 0.60384514, 0.60431816, 0.60399076,
       0.60355908, 0.6033557 , 0.60353887, 0.60373873, 0.60377824,
       0.6036423 , 0.6035281 , 0.60346444, 0.60355926, 0.60355743,
       0.60352678, 0.60351225, 0.60349947, 0.60353986, 0.60355537,
       0.60353544, 0.60356549, 0.60344009, 0.60348762, 0.60352828,
       0.60350413, 0.60347366, 0.60351414, 0.60350736, 0.60351101,
       0.60351628, 0.60350075, 0.60348829, 0.60350791, 0.60348438,
       0.60348428, 0.60344657, 0.60350068, 0.60344711, 0.60342504,
       0.60353116, 0.60342054, 0.60349783, 0.60348615, 0.60346382,
       0.60348061, 0.60348448, 0.60350517, 0.60352193, 0.60349982,
       0.60349525, 0.6034913 , 0.60347022, 0.6034841 , 0.60347216,
       0.60351414, 0.60347229, 0.6035088 , 0.60344904, 0.60350449,
       0.60346942, 0.60349077, 0.60349338, 0.6034158 , 0.60347747,
       0.60352443, 0.60346651, 0.60348579, 0.60344913, 0.6034477 ,
       0.60349403, 0.60345733, 0.60352833, 0.603445  , 0.60348